### PR TITLE
refactor(*): many fixes and refactors

### LINKED ISSUE #38: Feat(music): Add queue support
Note: this is not for configuring music settings (dj role, etc)

- Anyone with DJ role can access it and skip/add/etc songs
- Websocket connection for live interaction

unknown (2)

### LINKED ISSUE #76: Fix(music): Clear queue from Discord then skip from dashboard should show nothing is playing
From Kyra:

> Fix bug where you clear the queue from Discord and then skip from the dashboard, Skyra leaves as she finished playing all songs, but the website keeps the last song 'til you refresh it

### PR DESCRIPTION
**Pull request by Favna**
depends on https://github.com/skyra-project/skyra/pull/930

---

- Added a sitemap
- Refactored the way guild acronym is resolved, matching what is datamined from Discord
- Removed old DebouncedTextInput component
- Removed all remaining occurrances of styled-components
  - Removed now stale Dialog component
- Rewrote DialogTitle and Footer components to TypeScript
- Fixed typings in Slider and rewrote it to a single default export
- Fixed (some) typings in SelectDuration
- Use makeStyles in SelectMany and SelectOne components
- Fixed typings of label prop in SelectOne component
- Fixed WS_URL constant potentially being undefined
- Rewrote utils in TypeScript
  - Removed unused useTraceUpdate hook
- Refactored Links and Words components to use makeStyles instead of styled-components
- Rewrote Music page in TypeScript with a Functional component
  - Music now always autoplays, not only sporadically
  - Websocket events are properly typed, both on Skyra and skyra.pw
  - Events are properly handled, such as queue updates and playing updates. And many more fixes alike.

---

Fixes #76
Closes #38

### CODE REVIEW

File: src/meta/util.ts [hunk 1]
```diff
@@ -13,13 +12,13 @@ export function logOut() {
 	history.replace('/');
 }
 
-export const loadState = (key: string) => {
+export const loadState = <T = any>(key: string) => {
```
Comment (kyranet) [inline src/meta/util.ts:15]: This should return `unknown` and let it be casted afterwards.
